---
BESMAN_ORG: PSMRI
BESMAN_OSSP: HWC-API
BESMAN_OSSP_CLONE_PATH: $HOME/$BESMAN_OSSP
BESMAN_ANSIBLE_ROLES_PATH: $BESMAN_DIR/tmp/$BESMAN_OSSP/roles
BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-bes-java:Be-Secure/ansible-role-oah-maven:Be-Secure/ansible-role-oah-eclipse
BESMAN_OSS_TRIGGER_PLAYBOOK_PATH: $BESMAN_DIR/tmp/$BESMAN_OSSP
BESMAN_OSS_TRIGGER_PLAYBOOK: besman-$BESMAN_OSSP-BT-trigger-playbook.yaml
BESMAN_DISPLAY_SKIPPED_ANSIBLE_HOSTS: false
# Please add other variables as well as ansible variables here
openjdk_version: 8
eclipse_req_packages: snapd
eclipse_pin_fav: true