---
# If you wish to update the default configuration values, copy this file and place it under your home dir, under the same name.
# These variables are used to drive the installation of the environment script.
# The variables that start with BESMAN_ are converted to environment vars.
# If you wish to add any other vars that should be used globally, add the var using the below format.
# BESMAN_<var name>: <value>
# If you are not using any particular value, remove it or comment it(#).
#*** - These variables should not be removed, nor left empty.
# Used to mention where you should clone the repo from, default value is Be-Secure
BESMAN_ORG: Be-Secure

#  project/ml model/training dataset
BESMAN_ARTIFACT_TYPE: project 

# Name of artifact under assessment.
BESMAN_ARTIFACT_NAME: jackson-databind

# Version of artifact under assessment.
BESMAN_ARTIFACT_VERSION: jackson-databind-2.16.1_release

# Original source URL for the project under test.
BESMAN_ARTIFACT_ORIGIN_URL: https://github.com/Be-Secure/jackson-databind

# Source code url of artifact under assessment.
BESMAN_ARTIFACT_URL: https://github.com/Be-Secure/jackson-databind

# Name of environment.
BESMAN_ENV_NAME: jackson-databind-BT-env

# Path to clone source code of artifact under assessment.
# If you wish to change the clone path, provide the complete path.
BESMAN_ARTIFACT_DIR: $HOME/$BESMAN_ARTIFACT_NAME

# Path to download assessment and other required tools during installation.
BESMAN_TOOL_PATH: /opt

# Organization/lab/individual.
BESMAN_LAB_TYPE: Organization

# Name of lab owner. Default is Be-Secure.
BESMAN_LAB_NAME: Be-Secure

# Local dir to store assessment reports. Default is home.
BESMAN_ASSESSMENT_DATASTORE_DIR: $HOME/besecure-assessment-datastore

# Remote repo to store assessment reports.
BESMAN_ASSESSMENT_DATASTORE_URL: https://github.com/Be-Secure/besecure-assessment-datastore

# Path to download ansible role of assessment tools and other utilities
BESMAN_ANSIBLE_ROLES_PATH: $BESMAN_DIR/tmp/$BESMAN_ARTIFACT_NAME/roles

# List of tools to install. Tools are installed using ansible roles.# To get the list of ansible roles run 
#   $ bes list --role
# add the roles here. format - <Github id>/<repo name>,<Github id>/<repo name>,<Github id>/<repo name>,...
BESMAN_ANSIBLE_ROLES: Be-Secure/ansible-role-oah-java,Be-Secure/ansible-role-oah-maven,Be-Secure/ansible-role-oah-eclipse

# Path of the playbook with which we run the ansible roles.
# Default path is ~/.besman/tmp/<artifact name dir>/
BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH: $BESMAN_DIR/tmp/$BESMAN_ARTIFACT_NAME

# Name of trigger playbook which runs the ansible roles.
BESMAN_ARTIFACT_TRIGGER_PLAYBOOK: besman-$BESMAN_ARTIFACT_NAME-BT-trigger-playbook.yaml

# Display all the skipped steps, set it to true.
# Default value is false
BESMAN_DISPLAY_SKIPPED_ANSIBLE_HOSTS: false


# Default values of ansible roles will be present in their respective repos.
# Check https://github.com/Be-Secure/<repo of the ansible role>/blob/main/defaults/main.yml.
# To change the default values copy variable from https://github.com/Be-Secure/<repo of the ansible role>/blob/main/defaults/main.yml
# and paste it here and change the value.
# Format is <variable name>: <value> 
# Eg: openjdk_version: 11
