---
# If you wish to update the default configuration values, copy this file and place it under your home dir, under the same name.
# These variables are used to drive the installation of the environment script.
# The variables that start with BESMAN_ are converted to environment vars.
# If you wish to add any other vars that should be used globally, add the var using the below format.
# BESMAN_<var name>: <value>
# If you are not using any particular value, remove it or comment it(#).
#*** - These variables should not be removed, nor left empty.

# BESMAN_ARTIFACT_TYPE - project/ml model/training dataset
BESMAN_ARTIFACT_TYPE: ml model

# BESMAN_ARTIFACT_NAME - name of the artifact under assessment.
#BESMAN_ARTIFACT_NAME: ML #***

# BESMAN_ARTIFACT_VERSION - version of the artifact under assessment.
#BESMAN_ARTIFACT_VERSION: #Enter the version of the artifact here. #***

# BESMAN_ARTIFACT_URL - Source code url of the artifact under assessment.
#BESMAN_ARTIFACT_URL: https://github.com/Be-Secure/ML #***

#BESMAN_ENV_NAME - This variable stores the name of the environment file.
BESMAN_ENV_NAME: ML-RT-env #***

# BESMAN_ARTIFACT_DIR - The path where you wish to clone the source code of the artifact under assessment.
# If you wish to change the clone path, provide the complete path.
#BESMAN_ARTIFACT_DIR: $HOME/$BESMAN_ARTIFACT_NAME #***

# BESMAN_TOOL_PATH - The path where we download the assessment and other required tools during installation.
BESMAN_TOOL_PATH: /opt #***

# BESMAN_LAB_TYPE - Organization. This variable indicates the individual's lab affiliation
BESMAN_LAB_TYPE: Organization #***

# BESMAN_LAB_NAME - Name of the lab. Default is Be-Secure. This variable indicates the individual's lab affiliation
BESMAN_LAB_NAME: Be-Secure #***

# BESMAN_ASSESSMENT_DATASTORE_DIR - This is the local dir where we store the assessment reports. Default is home.
BESMAN_ASSESSMENT_DATASTORE_DIR: $HOME/besecure-ml-assessment-datastore #***

# BESMAN_ASSESSMENT_DATASTORE_URL - The remote repo where we store the assessment reports.
BESMAN_ASSESSMENT_DATASTORE_URL: https://github.com/Be-Secure/besecure-ml-assessment-datastore #***

# BESMAN_COUNTERFIT_URL - The remote repo from CounterFit will be installed.
BESMAN_COUNTERFIT_URL: https://github.com/Be-Secure/counterfit.git

# BESMAN_WATCHTOWER_URL - The remote repo from watchtower will be installed.
BESMAN_WATCHTOWER_URL: https://github.com/bosch-aisecurity-aishield/watchtower.git

# BESMAN_COUNTERFIT_BRANCH - The remote repo branch
BESMAN_COUNTERFIT_BRANCH: develop

# BESMAN_WATCHTOWER_BRANCH - The remote repo branch
BESMAN_WATCHTOWER_TAG: v1.0.0

# BESMAN_COUNTERFIT_LOCAL_PATH - Path of counterfit dir in user system.
BESMAN_COUNTERFIT_LOCAL_PATH: $HOME/counterfit

# BESMAN_REPO_TYPE - Type of repo user want to scan using watchtower [options: github, huggingface]
BESMAN_REPO_TYPE: "github"

# BESMAN_REPO_URL - model repo url for watchtower execution
BESMAN_REPO_URL: "https://github.com/asa1997/bes-image-classification" 

BESMAN_BRANCH_NAME: "main"          
BESMAN_DEPTH_VAL: "1"             
BESMAN_ARTIFACT_NAME: "bes-image-classification"
BESMAN_WATCHTOWER_PATH: "$HOME/watchtower"