---
# If you wish to update the default configuration values, copy this file and place it under your home dir, under the same name.
# These variables are used to drive the installation of the environment script.
# The variables that start with BESMAN_ are converted to environment vars.
# If you wish to add any other vars that should be used globally, add the var using the below format.
# BESMAN_<var name>: <value>
# If you are not using any particular value, remove it or comment it(#).
#*** - These variables should not be removed, nor left empty.

# Project/ml model/training dataset
BESMAN_ARTIFACT_TYPE: model

# Name of the artifact under assessment.
#BESMAN_ARTIFACT_NAME: ML #***

# Version of the artifact under assessment.
#BESMAN_ARTIFACT_VERSION: #Enter the version of the artifact here. #***

# Source code url of the artifact under assessment.
#BESMAN_ARTIFACT_URL: https://github.com/Be-Secure/ML #***

#BESMAN_ENV_NAME - This variable stores the name of the environment file.
BESMAN_ENV_NAME: ML-RT-env #***

# The path where you wish to clone the source code of the artifact under assessment.
# If you wish to change the clone path, provide the complete path.
#BESMAN_ARTIFACT_DIR: $HOME/$BESMAN_ARTIFACT_NAME #***

# The path where we download the assessment and other required tools during installation.
BESMAN_TOOL_PATH: /opt #***

# Organization. This variable indicates the individual's lab affiliation
BESMAN_LAB_TYPE: Organization #***

# Name of the lab. Default is Be-Secure. This variable indicates the individual's lab affiliation
BESMAN_LAB_NAME: Be-Secure #***

# This is the local dir where we store the assessment reports. Default is home.
BESMAN_ASSESSMENT_DATASTORE_DIR: $HOME/besecure-ml-assessment-datastore #***

# The remote repo where we store the assessment reports.
BESMAN_ASSESSMENT_DATASTORE_URL: https://github.com/Be-Secure/besecure-ml-assessment-datastore #***

# The remote repo from CounterFit will be installed.
BESMAN_COUNTERFIT_URL: https://github.com/Be-Secure/counterfit.git

# The remote repo from watchtower will be installed.
BESMAN_WATCHTOWER_URL: https://github.com/bosch-aisecurity-aishield/watchtower.git

# The remote repo branch
BESMAN_COUNTERFIT_BRANCH: develop

# The remote repo branch
BESMAN_WATCHTOWER_TAG: v1.0.0

# Watchtower tool path in user system
BESMAN_WATCHTOWER_PATH: "$HOME/watchtower" # it is the default path, don't change it until required

# Path of counterfit dir in user system.
BESMAN_COUNTERFIT_LOCAL_PATH: $HOME/counterfit


### Watchtower execution variables
### ------------------------------

# Type of repo user want to scan using Watchtower [options: github, huggingface]
BESMAN_TARGET_REPO_TYPE: ""

# Model repo url for watchtower execution [github / huggingface url]
BESMAN_TARGET_REPO_URL: "" 

# Branch name of target repo for watchtower execution (applicable for GitHub only)
BESMAN_TARGET_BRANCH_NAME: "main"  

# Default value is 1 (applicable fir GitHub URL only)
BESMAN_TARGET_DEPTH_VAL: "1"    


