---
# If you wish to update the default configuration values, copy this file and place it under your home dir, under the same name.
# These variables are used to drive the installation of the environment script.
# The variables that start with BESMAN_ are converted to environment vars.
# If you wish to add any other vars that should be used globally, add the var using the below format.
# BESMAN_<var name>: <value>
# If you are not using any particular value, remove it or comment it(#).
#*** - These variables should not be removed, nor left empty.
# used to mention where you should clone the repo from, default value is Be-Secure
BESMAN_ORG: Be-Secure #***

# project/ml model/training dataset
BESMAN_ARTIFACT_TYPE: project #***

# Name of the artifact under assessment.
BESMAN_ARTIFACT_NAME: instructlab #***

# Version of the artifact under assessment.
BESMAN_ARTIFACT_VERSION: 0.22.1 #***

# Original source URL for the project under test.
BESMAN_ARTIFACT_ORIGIN_URL: https://github.com/Be-Secure/instructlab

# Source code url of the artifact under assessment.
BESMAN_ARTIFACT_URL: https://github.com/Be-Secure/instructlab #***

# This variable stores the name of the environment file.
BESMAN_ENV_NAME: instructlab-RT-env #***

# The path where you wish to clone the source code of the artifact under assessment.
# If you wish to change the clone path, provide the complete path.
BESMAN_ARTIFACT_DIR: $HOME/$BESMAN_ARTIFACT_NAME #***

# The path where we download the assessment and other required tools during installation.
BESMAN_TOOL_PATH: /opt #***

# Organization/lab/individual.
BESMAN_LAB_TYPE: Organization #***

# Name of the owner of the lab. Default is Be-Secure.
BESMAN_LAB_NAME: Be-Secure #***

# Mode for scorecard cli or github action.
BESMAN_SCORECARD_ASSESSMENT_MODE: "github-action"

# This is the local dir where we store the assessment reports. Default is home.
BESMAN_ASSESSMENT_DATASTORE_DIR: $HOME/besecure-assessment-datastore #***

# The remote repo where we store the assessment reports.
BESMAN_ASSESSMENT_DATASTORE_URL: https://github.com/Be-Secure/besecure-assessment-datastore #***

# The path where we download the ansible role of the assessment tools and other utilities
#BESMAN_ANSIBLE_ROLES_PATH: $BESMAN_DIR/tmp/$BESMAN_ARTIFACT_NAME/roles #***

# The list of tools you wish to install. The tools are installed using ansible roles.
# To get the list of ansible roles run 
#   $ bes list --role
#add the roles here. format - <Github id>/<repo name>,<Github id>/<repo name>,<Github id>/<repo name>,... #***
#BESMAN_ANSIBLE_ROLES: 

# sets the path of the playbook with which we run the ansible roles.
# Default path is ~/.besman/tmp/<artifact name dir>/
#BESMAN_ARTIFACT_TRIGGER_PLAYBOOK_PATH: $BESMAN_DIR/tmp/$BESMAN_ARTIFACT_NAME #***

# Name of the trigger playbook which runs the ansible roles.
#BESMAN_ARTIFACT_TRIGGER_PLAYBOOK: besman-$BESMAN_ARTIFACT_NAME-RT-trigger-playbook.yaml #***

# If the users likes to display all the skipped steps, set it to true.
# Default value is false
#BESMAN_DISPLAY_SKIPPED_ANSIBLE_HOSTS: false #***

# The default values of the ansible roles will be present in their respective repos.
# You can go to https://github.com/Be-Secure/<repo of the ansible role>/blob/main/defaults/main.yml.
# If you wish to change the default values copy the variable from the https://github.com/Be-Secure/<repo of the ansible role>/blob/main/defaults/main.yml
# and paste it here and change the value.
# Format is <variable name>: <value> 
# Eg: openjdk_version: 11

BESMAN_ASSESSMENT_TOOLS: scorecard,criticality_score,sonarqube,spdx-sbom-generator,fossology,cyclonedx-sbom-generator
BESMAN_SPDX_SBOM_ASSET_URL: https://github.com/opensbom-generator/spdx-sbom-generator/releases/download/v0.0.15/spdx-sbom-generator-v0.0.15-linux-amd64.tar.gz

